hydra:
  job:
    chdir: false

model_name: ???
output_file: ???

defaults:
  - task_config: spider
  - model_config: api_gen_a

dataset_reader:
  _target_: src.dataset_readers.inference_dsr.InferenceDatasetReader
  dataset_path: null
  dataset_split: null
  ds_size: null
  task_name: ${task_config.task_name}
  model_name: ${model_name}
  n_tokens: 8000
  field: ${model_config.field}
  index_reader: ${index_reader}

index_reader:
  _target_: src.dataset_readers.index_dsr.IndexDatasetReader
  task_name: ${task_config.task_name}
  model_name: ${model_name}
  field: ${model_config.index_field}
  dataset_path: ???
